<?php

namespace AppBundle\Repository;

/**
 * FrameworkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrameworkRepository extends \Doctrine\ORM\EntityRepository
{
}
