<?php

namespace AppBundle\Repository;

/**
 * IdeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdeRepository extends \Doctrine\ORM\EntityRepository
{
}
