<?php

namespace AppBundle\Repository;

/**
 * SuperProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuperProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
