<?php

namespace AppBundle\Repository;

/**
 * TaskLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskLineRepository extends \Doctrine\ORM\EntityRepository
{
}
